const actions = {
  USER_UPDATE_CONTEXT: 'USER.UPDATE_USER_CONTEXT',

  CLIENT_UPDATE_CLIENT_LIST: 'CLIENT_UPDATE_CLIENT_LIST',

  NOTIFICATION_PUSH: 'NOTIFICATION.PUSH',
  NOTIFICATION_DISMISS: 'NOTIFICATION.DISMISS',
};

export {
  actions,
};

export default {
  actions,
};
